- Expertise in Investment Risk Model: Transitioned from Life Insurance model to Investment Risk model in June 2024. In a short span of 5 months, became an active contributor and developer of IvR model.
 - Delivered all Business-as-Usual (BAU) tasks consistently within set timeframes.
- Ensured accuracy and reliability, maintaining a record free from operational issues or delays.
- Actively identified and implemented improvements in the Investment Risk (IvR) model’s methodology and execution.
 - Actively raising issues with IT to address high memory consumption challenges in model implementation and dataset read